import { app, type BrowserWindow } from 'electron'
import { writeFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { notifyHookPath } from '../notify-hook'

// Env-gated END-TO-END verdict smoke (MOGGING_VERDICTLIVE=1).
//
// Everything else about the alerts system is gated against a SEAM. ATTENTION unit-asserts the
// tracker in-process and drives the UI through `__mogging.attention.setPaneState`. NOTIFYHOOK
// proves the generated hook script speaks the wire — but to a FAKE daemon socket, with no window.
// So the middle of the chain, which is the part a user actually has, was never exercised by
// anything: a real hook event, over the real authed socket, into the real daemon's real tracker,
// out through the real IPC relay, onto the real dot.
//
// This gate closes that. It runs THE LITERAL COMMAND CLAUDE CODE RUNS inside a real pane:
//
//     node "<userData>/notify-hook/notify.mjs" --event done
//
// which is exactly what `claudeNotifyHooks` writes into the `--settings` overlay for the Stop
// hook (agents/notify-hook.ts). Nothing is simulated: the script resolves MOGGING_PANE_ID and
// MOGGING_DAEMON_ENDPOINT from the environment the PANE really has, opens the daemon's socket,
// handshakes with the token, and sends the notify. If any link in that chain is wrong, the dot
// does not move and this gate goes red.
//
// THE DRIVE MODELS A REAL AGENT: one long-lived DRIVER process owns the pane's foreground for
// the whole ladder and fires the hook script for each event name typed at it (stdin). It used
// to type each hook invocation as its own shell command — but every command's exit prints a
// PROMPT, and a prompt is now a verdict (activity.ts shellPrompt): the foreground program is
// gone, so busy/attention die with it. Real hooks fire while the agent RUNS — no prompt lands
// between events — and the driver reproduces exactly that. (The prompt heal has its own
// end-to-end assert in the STATE gate.)
//
// The story it drives is the one that matters, and the one that used to be told wrong:
//
//   turn-start        you submit a prompt                  -> busy
//   subagent-start x2 the agent fans work out              -> busy
//   done              THE MAIN ENDS ITS TURN MID-FAN-OUT   -> STILL BUSY. This is the whole
//                     (Claude fires Stop with the work        subagent gate: green requires
//                      still in flight)                       main-done AND zero subagents, so
//                                                             the verdict is DEFERRED, not taken.
//                                                             Get this wrong and a pane pulses
//                                                             green in the middle of a job.
//   subagent-stop     one child lands                      -> still busy
//   subagent-stop     the last child lands                 -> GREEN. The main's own deferred
//                                                             verdict is now due.
//   click             you look at it                       -> acknowledged, back to yellow
//   needs-input       a permission prompt                  -> RED + a red resting outline
//   arrow key         navigation                           -> STILL RED. It answered nothing —
//                                                             only content answers (a printable
//                                                             or Enter; every permission dialog
//                                                             takes single-key answers).
//   Enter             you actually answer it               -> busy. The agent said it was
//                                                             blocked on this human; the human
//                                                             answered. Both facts certain.
//
// THE ADOPTED SESSION IS ON A CLOCK. The dot only renders for a pane with an agent session, and
// `agents.adopt` is a shim — no claude is really running in that pane, so the backend's PTY-subtree
// detector emits agentId:null and retires it under us. Every wait therefore RE-ADOPTS on each
// poll. That is not a workaround for a flake: re-adopting forces the pane to PULL state from the
// daemon (terminal:stateSync), so each assert reads the daemon's own truth rather than a UI echo
// of the event we just sent — which makes this a stronger test, not a weaker one.

/** The driver: reads event names from the pane's stdin, runs the REAL hook script for each —
 *  the agent-shaped process a CLI actually is while its hooks fire. Generated next to the hook
 *  script; plain node, no quoting hell through the pane's shell. */
const DRIVER_SOURCE = `// MoggingLabs VERDICTLIVE driver - GENERATED by the smoke, not shipped.
// RAW MODE + terminal:false + a whitelist, all three load-bearing. Cooked stdin turned the
// smoke's arrow-key probe into a HISTORY RECALL of 'needs-input' — first readline's own line
// editor, then (with that disabled) ConPTY's console-level line input did the same one layer
// down — so the Enter that was supposed to ANSWER the red resubmitted the block instead, for
// real. Raw mode is also simply the honest model: a real agent TUI runs its pane in raw mode,
// which is why arrow keys reach a real CLI as bytes and not as console history. The whitelist
// is the last line: latch probes (arrows, bare Enter) must never reach the hook as made-up
// event names — an unknown EXPLICIT notify rings attention by design.
import { spawn } from 'node:child_process'
import { createInterface } from 'node:readline'
const hook = process.argv[2]
const EVENTS = new Set(['turn-start', 'subagent-start', 'subagent-stop', 'done', 'needs-input', 'idle-prompt', 'busy', 'idle', 'notice'])
if (process.stdin.isTTY) process.stdin.setRawMode(true)
const rl = createInterface({ input: process.stdin, terminal: false })
rl.on('line', (l) => {
  const ev = l.trim()
  if (ev === 'exit') process.exit(0)
  if (!EVENTS.has(ev)) return
  const p = spawn(process.execPath, [hook, '--event', ev], { stdio: 'ignore' })
  p.on('error', () => {})
})
`

const SCRIPT = (driver: string, hook: string): string => `(async () => {
  const sleep = (ms) => new Promise((r) => setTimeout(r, ms))
  const m = window.__mogging
  if (!m || !m.workspace || !m.agents) return { pass: false, error: 'no dev handles' }
  if (m.workspace.count() === 0) { m.workspace.create({ name: 'Verdict' }); await sleep(1200) }

  const DRIVER = ${JSON.stringify(driver)}
  const HOOK = ${JSON.stringify(hook)}
  const type = (s) => window.bridge.send('terminal:write', { id: 1, data: s })
  // One foreground process for the whole ladder — the shape of a real agent. Each event name
  // typed below reaches ITS stdin (never the shell), and it runs the hook's real invocation.
  const fire = (ev) => type(ev + '\\r')
  const adopt = () => { try { m.agents.adopt(1, 'claude', '') } catch (e) {} }

  const slot = () => document.querySelector('.layout-slot[data-pane-id="1"]')
  const dot = () => { const e = slot() && slot().querySelector('.pane-state'); return e ? e.getAttribute('data-state') : null }
  const alert = () => { const s = slot(); return s ? s.getAttribute('data-alert') : null }

  const steps = []
  /** Poll until the dot reaches \`want\`, re-adopting each tick so the shim session cannot be
   *  retired out from under us and each read re-pulls from the daemon. */
  const settle = async (want, ms) => {
    const t0 = Date.now()
    let got = dot()
    while (Date.now() - t0 < (ms || 12000)) {
      adopt()
      await sleep(300)
      got = dot()
      if (got === want) break
    }
    const s = { want, got, alert: alert(), ok: got === want }
    steps.push(s)
    return s
  }
  /** Assert the dot HOLDS a state for a while — the deferred-done case is about what must NOT
   *  happen, and a poll that stops at the first match would never see it. */
  const hold = async (want, ms) => {
    const t0 = Date.now()
    let got = dot()
    while (Date.now() - t0 < ms) {
      adopt()
      await sleep(300)
      got = dot()
      if (got !== want) break // it moved — that IS the failure
    }
    const s = { want, got, alert: alert(), ok: got === want }
    steps.push(s)
    return s
  }

  adopt()
  await sleep(1200)

  // Launch the driver: from here until 'exit' it owns the pane's foreground, like an agent.
  type('node "' + DRIVER + '" "' + HOOK + '"\\r')
  await sleep(2500) // node boot + readline attach (typed lines buffer in the PTY meanwhile)

  // ── a real turn, fanning out to subagents ────────────────────────────────────────────
  fire('turn-start')
  const turnStart = await settle('busy')

  fire('subagent-start')
  await sleep(900)
  fire('subagent-start')
  const fanOut = await settle('busy')

  // THE GATE. The main fires Stop with two children still running. It must NOT go green.
  fire('done')
  const doneDeferred = await hold('busy', 5000)

  fire('subagent-stop')
  const oneLeft = await hold('busy', 3500)

  // ...and the last child landing is what makes the main's own verdict due.
  fire('subagent-stop')
  const redeemed = await settle('finished')

  // A click is the acknowledgement.
  const s = slot()
  if (s) s.dispatchEvent(new MouseEvent('mousedown', { bubbles: true }))
  const acked = await settle('idle', 4000)

  // ── a permission prompt ──────────────────────────────────────────────────────────────
  fire('needs-input')
  const blocked = await settle('attention')

  // Navigation answers nothing: an arrow key must hold the red (content would clear it —
  // that is the answer rule, unit-gated in ATTENTION and integration-gated in STATE).
  type('\\x1b[A')
  const strayHolds = await hold('attention', 4000)

  // Enter answers it.
  type('\\r')
  const answered = await settle('busy', 8000)

  type('exit\\r') // release the pane; the prompt that follows lands after every assert above

  const pass = steps.every((s) => s.ok) &&
    doneDeferred.got === 'busy' &&      // never green mid-fan-out
    redeemed.alert === 'finished' &&    // the resting green outline
    blocked.alert === 'input' &&        // the resting red outline
    acked.alert === null                // the click cleared it

  return {
    pass,
    turnStart, fanOut, doneDeferred, oneLeft, redeemed, acked, blocked, strayHolds, answered
  }
})()`

export function runVerdictLiveSmoke(win: BrowserWindow): void {
  setTimeout(() => app.exit(1), 120000) // real subprocess spawns per step — be generous
  const run = async (): Promise<void> => {
    let result: unknown = { pass: false, error: 'never ran' }
    const hook = notifyHookPath()
    let driver: string | null = null
    try {
      if (!hook) throw new Error('no notify-hook script (it could not be written)')
      driver = join(dirname(hook), 'verdictlive-driver.mjs')
      writeFileSync(driver, DRIVER_SOURCE)
      result = await win.webContents.executeJavaScript(SCRIPT(driver, hook), true)
      ;(result as { hook?: string }).hook = hook
    } catch (e) {
      result = { pass: false, error: String(e), hook, driver }
    }
    try {
      writeFileSync(join(process.cwd(), 'out', 'verdictlive-result.json'), JSON.stringify(result))
    } catch {
      /* best effort */
    }
    console.log('VERDICTLIVE_RESULT ' + JSON.stringify(result))
    app.exit((result as { pass?: boolean })?.pass ? 0 : 1)
  }
  if (win.webContents.isLoading()) win.webContents.once('did-finish-load', () => setTimeout(run, 3000))
  else setTimeout(run, 3000)
}
