import { LAUNCH_INTENT_VERSION, normalizeLaunchIntent, type PaneLaunchIntent } from '@contracts'
import { AGENT_CLI_REGISTRY, type AgentCliDefinition } from '../../core/agent-clis'

/**
 * Recover launch intent from a pre-migration `panes.command` string.
 *
 * THE ONLY PLACE a legacy command line is ever read. Written as the strict INVERSE of
 * features/agents/launch.ts `buildLaunchCommand`, whose three prefix grammars this mirrors
 * one-for-one:
 *
 *   cmd         cd /d "<cwd>" &&        set "K=V" &&
 *   powershell  Set-Location '<cwd>' -ErrorAction Stop;   $env:K='V';
 *   posix       cd '<cwd>' &&           export K='V' &&
 *
 * The agent is the first token AFTER those prefixes, matched against the registry's `bin`
 * names. That distinction is the entire bug this repo shipped: the old `resumeCommandFor`
 * matched `command.split(/\s+/)[0]`, which is `cd` for every command the app has ever built,
 * so it resumed nothing and lost every profile. Matching a registry bin — never a hard-coded
 * table — also keeps this honest as CLIs are added.
 *
 * Deliberately DISCARDED: `--settings` / `--mcp-config` paths, bell and title args. Those are
 * regenerated by the composer and are content-addressed by digest; carrying a stale path
 * forward is a second-order bug, not fidelity.
 *
 * This runs read-side (session-rows.ts `rowToPane`) only for rows written before the intent
 * columns existed, and the daemon's first persist promotes the result into real columns — so
 * it self-extinguishes rather than needing a migration ledger that can half-run.
 */

type Dialect = 'cmd' | 'powershell' | 'posix'

/** POSIX `'…'` with the `'\''` dance (shq). */
function readShq(s: string, start: number): { value: string; next: number } | null {
  if (s[start] !== "'") return null
  let out = ''
  let i = start + 1
  while (i < s.length) {
    if (s[i] === "'") {
      if (s.startsWith("'\\''", i)) {
        out += "'"
        i += 4
        continue
      }
      return { value: out, next: i + 1 }
    }
    out += s[i]
    i++
  }
  return null
}

/** PowerShell `'…'` with embedded quotes doubled (psq). */
function readPsq(s: string, start: number): { value: string; next: number } | null {
  if (s[start] !== "'") return null
  let out = ''
  let i = start + 1
  while (i < s.length) {
    if (s[i] === "'") {
      if (s[i + 1] === "'") {
        out += "'"
        i += 2
        continue
      }
      return { value: out, next: i + 1 }
    }
    out += s[i]
    i++
  }
  return null
}

/** cmd.exe `"…"` — cdPrefix/envPrefix interpolate raw, so read to the next quote. */
function readCmdQuoted(s: string, start: number): { value: string; next: number } | null {
  if (s[start] !== '"') return null
  const end = s.indexOf('"', start + 1)
  return end === -1 ? null : { value: s.slice(start + 1, end), next: end + 1 }
}

/** The `cd` prefix, which also tells us which shell dialect composed the rest. */
function takeCwd(cmd: string): { cwd: string; rest: string; dialect: Dialect } | null {
  if (cmd.startsWith('cd /d ')) {
    const r = readCmdQuoted(cmd, 'cd /d '.length)
    if (!r || !cmd.startsWith(' && ', r.next)) return null
    return { cwd: r.value, rest: cmd.slice(r.next + 4), dialect: 'cmd' }
  }
  if (cmd.startsWith('Set-Location ')) {
    const r = readPsq(cmd, 'Set-Location '.length)
    if (!r || !cmd.startsWith(' -ErrorAction Stop; ', r.next)) return null
    return { cwd: r.value, rest: cmd.slice(r.next + ' -ErrorAction Stop; '.length), dialect: 'powershell' }
  }
  if (cmd.startsWith('cd ')) {
    const r = readShq(cmd, 'cd '.length)
    if (!r || !cmd.startsWith(' && ', r.next)) return null
    return { cwd: r.value, rest: cmd.slice(r.next + 4), dialect: 'posix' }
  }
  // buildLaunchCommand emits no cd prefix for an empty cwd. Still parseable — the cwd is
  // simply unknown here and the row's own `cwd` column stands.
  return null
}

const ENV_KEY = /^[A-Za-z_][A-Za-z0-9_]*$/

/** Zero or more env-pointer assignments in the dialect the cd prefix established. */
function takeEnv(rest: string, dialect: Dialect): { env: Record<string, string>; rest: string } {
  const env: Record<string, string> = {}
  let s = rest
  for (;;) {
    if (dialect === 'cmd' && s.startsWith('set "')) {
      const r = readCmdQuoted(s, 'set '.length)
      if (!r || !s.startsWith(' && ', r.next)) break
      const eq = r.value.indexOf('=')
      if (eq <= 0) break
      const key = r.value.slice(0, eq)
      if (!ENV_KEY.test(key)) break
      env[key] = r.value.slice(eq + 1)
      s = s.slice(r.next + 4)
      continue
    }
    if (dialect === 'powershell' && s.startsWith('$env:')) {
      const eq = s.indexOf('=')
      if (eq === -1) break
      const key = s.slice('$env:'.length, eq)
      if (!ENV_KEY.test(key)) break
      const r = readPsq(s, eq + 1)
      if (!r || !s.startsWith('; ', r.next)) break
      env[key] = r.value
      s = s.slice(r.next + 2)
      continue
    }
    if (dialect === 'posix' && s.startsWith('export ')) {
      const eq = s.indexOf('=')
      if (eq === -1) break
      const key = s.slice('export '.length, eq)
      if (!ENV_KEY.test(key)) break
      const r = readShq(s, eq + 1)
      if (!r || !s.startsWith(' && ', r.next)) break
      env[key] = r.value
      s = s.slice(r.next + 4)
      continue
    }
    break
  }
  return { env, rest: s }
}

const SESSION_ID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i

/**
 * The intent behind a legacy command string, or null when it does not describe a known agent
 * (a plain shell pane, an unparseable line, or a CLI we do not know). NEVER throws: a row that
 * cannot be read must restore as it does today, never take the daemon down at boot.
 *
 * `cwd` is the row's own persisted cwd, used when the command carries no `cd` prefix —
 * buildLaunchCommand omits it for an empty cwd, and a hand-set `run: 'claude'` has none
 * either. The command's cwd wins when present: it is what the agent actually started in.
 */
export function parseLegacyLaunchCommand(
  command: string | null | undefined,
  opts: { cwd?: string; at?: number } = {}
): PaneLaunchIntent | null {
  if (!command || typeof command !== 'string') return null
  try {
    const head = takeCwd(command)
    const afterCwd = head ? head.rest : command
    const { env, rest } = head ? takeEnv(head.rest, head.dialect) : { env: {}, rest: afterCwd }

    const tokens = rest.trim().split(/\s+/)
    const bin = tokens[0]
    if (!bin) return null
    // Widened to the interface on purpose: the registry is `as const`, so a bare find()
    // yields a union in which the CLIs without a config home (aider, opencode) have no
    // `pointerEnv` member at all.
    const def: AgentCliDefinition | undefined = AGENT_CLI_REGISTRY.find((d) => d.bin === bin)
    if (!def) return null

    const pointer = def.config.pointerEnv
    const configDir = pointer ? env[pointer] : undefined

    // A session id only ever follows the adapter's resume flag ("claude --resume <uuid>").
    let sessionId: string | undefined
    const resumeHead = def.resumeArgs?.[0]
    if (resumeHead) {
      const at1 = tokens.indexOf(resumeHead)
      const candidate = at1 !== -1 ? tokens[at1 + 1] : undefined
      if (candidate && SESSION_ID.test(candidate)) sessionId = candidate
    }

    return normalizeLaunchIntent({
      v: LAUNCH_INTENT_VERSION,
      agentId: def.id,
      cwd: head?.cwd || opts.cwd || undefined,
      configDir,
      sessionId,
      source: 'legacy',
      at: opts.at ?? 0
    })
  } catch {
    return null
  }
}
