# Generated by scripts/update-manifests.mjs — edit the templates there, not here.
cask "mogginglabs-workspace" do
  version "0.10.0"
  sha256 "4ae1943af022fd6e040e505f574077358d7565a353d2c9d59c994755b615f13b"

  url "https://github.com/MoggingLabs/mogginglabs-workspace/releases/download/v#{version}/MoggingLabs.Workspace-#{version}-mac-arm64.dmg"
  name "MoggingLabs Workspace"
  desc "Multi-pane terminal workspace for AI coding agents"
  homepage "https://github.com/MoggingLabs/mogginglabs-workspace"

  auto_updates true
  depends_on arch: :arm64
  depends_on macos: :big_sur

  app "MoggingLabs Workspace.app"

  zap trash: [
    "~/Library/Application Support/MoggingLabs Workspace",
    "~/Library/Application Support/MoggingLabs",
    "~/Library/Preferences/ai.mogginglabs.workspace.plist",
    "~/Library/Saved Application State/ai.mogginglabs.workspace.savedState",
  ]
end
