# Generated by scripts/update-manifests.mjs — edit the templates there, not here.
cask "mogginglabs-workspace" do
  version "0.14.0"
  sha256 "a099c1b146afa615459fbef5b5a93e4ba6f79ece85f2d0588c080feb860350c5"

  url "https://github.com/MoggingLabs/mogginglabs-workspace/releases/download/v#{version}/MoggingLabs-Workspace-#{version}-mac-arm64.dmg"
  name "MoggingLabs Workspace"
  desc "Multi-pane terminal workspace for AI coding agents"
  homepage "https://github.com/MoggingLabs/mogginglabs-workspace"

  auto_updates true
  depends_on arch: :arm64
  depends_on macos: :big_sur

  app "MoggingLabs Workspace.app"

  zap trash: [
    "~/Library/Application Support/MoggingLabs Workspace",
    "~/Library/Application Support/MoggingLabs",
    "~/Library/Preferences/ai.mogginglabs.workspace.plist",
    "~/Library/Saved Application State/ai.mogginglabs.workspace.savedState",
  ]
end
