import { app } from 'electron'
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { homedir } from 'node:os'
import { parse as parseJsonc } from 'jsonc-parser'
import {
  NOTIFY_HOOK_SOURCE,
  aiderBellEnv,
  codexBellArgs,
  geminiSystemSettings,
  opencodeConfig,
  opencodePluginSource,
  opencodeTuiConfig
} from '@backend/features/agents'

// App-wiring for the "always rings the bell" layer (backend/features/agents/
// notify-hook.ts): write the generated notify script + per-CLI config files into
// userData once per run, and hand every launch the session-scoped args/env its CLI
// needs to ring the pane — never a write to the user's own config files. Same
// lifecycle as the context relay next door. Claude's share of this rides its
// generated --settings file (src/main/context.ts).

let scriptPath: string | null = null
/** The notify script's bytes were CONTENT-verified this app run (see notifyHookPath). */
let scriptVerified = false
/** userData/notify-hook exists this run — one mkdir instead of one per generated file. */
let hookDirReady = false
/** Generated file name -> the bytes this run last wrote there. A hit + the file still
 *  on disk means the target already holds exactly these bytes; anything else re-reads
 *  and re-compares before writing, so a change always lands. */
const generatedMemo = new Map<string, string>()

/**
 * Gate seam (the context relay's twin — src/main/context.ts): forget that this RUN
 * already content-verified the generated files, so the next path resolution compares
 * again. The guarantee being gated is about a run's FIRST resolution — a notify script
 * left by a previous release, whose baked-in channel segment would write session identity
 * into a directory this build's monitor never reads. Inert in production.
 */
export function resetNotifyVerificationForSmoke(): void {
  scriptVerified = false
  generatedMemo.clear()
}

/** The file's current bytes, or null when absent/unreadable (either answer means
 *  "write it") — the context relay's readRelay twin (src/main/context.ts). */
function readGeneratedBytes(file: string): string | null {
  try {
    return readFileSync(file, 'utf8')
  } catch {
    return null
  }
}

/** userData/notify-hook, created once per run. */
function hookDir(): string {
  const dir = join(app.getPath('userData'), 'notify-hook')
  if (!hookDirReady) {
    mkdirSync(dir, { recursive: true })
    hookDirReady = true
  }
  return dir
}

/** Write (idempotently) the generated notify script and return its absolute path —
 *  null on any filesystem failure (a launch must never break over the bell).
 *  CONTENT-checked once per RUN, then existence-checked: the context sink's channel
 *  segment is BAKED into the generated bytes (DAEMON_PROTOCOL_VERSION interpolation,
 *  the session-start branch), so a script written by a previous protocol would keep
 *  pushing session identity into the OLD channel's dir while this app's monitor reads
 *  the new one — the exact rot the context relay healed first (src/main/context.ts).
 *  That heal is a first-launch fact: NOTIFY_HOOK_SOURCE is a constant of this build,
 *  so once a run has reconciled the file, re-reading it per launch can only confirm
 *  what it already knows. The existence check still covers userData cleared mid-run
 *  (the failure that motivated the old existence check), and a miss re-arms the
 *  content verify instead of assuming. The user's own global hooks reference this
 *  path from their settings files (agent-global-hooks.ts), so it is rewritten IN
 *  PLACE, never renamed. */
export function notifyHookPath(): string | null {
  try {
    const file = scriptPath ?? join(hookDir(), 'notify.mjs')
    if (!scriptVerified || !existsSync(file)) {
      if (readGeneratedBytes(file) !== NOTIFY_HOOK_SOURCE) writeFileSync(file, NOTIFY_HOOK_SOURCE)
      scriptVerified = true
    }
    scriptPath = file
    return scriptPath
  } catch {
    scriptVerified = false // a failed write must never leave a "verified" lie behind
    hookDirReady = false
    return null
  }
}

/** The shell invocation a CLI hook should run (`node "<script>"`). Double quotes
 *  parse the same in PowerShell, Git bash, and POSIX sh — the shells CLIs use for
 *  command hooks. Null when the script could not be written. */
export function notifyHookInvocation(): string | null {
  const p = notifyHookPath()
  return p ? `node "${p}"` : null
}

/** Materialize (idempotently) the generated OpenCode notify plugin and return its path —
 *  null on any filesystem failure. Launches write it per-launch via bellLaunchExtras; the
 *  GLOBAL wiring needs it to exist regardless of launches, because the user's own
 *  opencode.json points at it by file:// spec (agent-global-hooks.ts). */
export function opencodeNotifyPluginPath(): string | null {
  const script = notifyHookPath()
  if (!script) return null
  return writeGenerated('opencode-notify-plugin.mjs', opencodePluginSource(script))
}

/** Read a JSON file that may not exist (or may be junk) — the merge bases below. */
function readJson(path: string): unknown {
  try {
    return JSON.parse(readFileSync(path, 'utf8'))
  } catch {
    return undefined
  }
}

/** Write a generated per-CLI config into userData/notify-hook, returning its path
 *  (null on failure — the launch proceeds without the bell, baseline still applies).
 *
 *  WRITE ONLY WHEN THE BYTES DIFFER. These files (gemini's system settings, opencode's
 *  tui.json and plugin) are regenerated on every launch from inputs that rarely move,
 *  so the old unconditional write meant four disk writes per launch to restate what
 *  was already there. The memo is the fast path (this run wrote these bytes AND the
 *  file is still on disk); on a miss the file is re-read and compared, so an
 *  externally edited or userData-cleared file is always re-established. Only a
 *  SUCCESSFUL write is remembered. */
function writeGenerated(name: string, content: string): string | null {
  try {
    const file = join(hookDir(), name)
    if (generatedMemo.get(name) === content && existsSync(file)) return file
    if (readGeneratedBytes(file) !== content) writeFileSync(file, content)
    generatedMemo.set(name, content)
    return file
  } catch {
    generatedMemo.delete(name)
    hookDirReady = false
    return null
  }
}

/** Gemini's REAL system-settings path per platform — merged through so our override
 *  file never masks an admin's policy (see geminiSystemSettings). */
function geminiRealSystemSettingsPath(): string {
  if (process.env.GEMINI_CLI_SYSTEM_SETTINGS_PATH) return process.env.GEMINI_CLI_SYSTEM_SETTINGS_PATH
  if (process.platform === 'win32') return 'C:\\ProgramData\\gemini-cli\\settings.json'
  if (process.platform === 'darwin') return '/Library/Application Support/GeminiCli/settings.json'
  return '/etc/gemini-cli/settings.json'
}

/** Session-scoped launch extras that make a provider ring its pane's bell: extra
 *  launch ARGS and/or env vars, per the CLI's own dialect. Claude is wired in
 *  claudeStatuslineArgs (context.ts); aider and codex additionally run the generated
 *  notify script, which is what lets their COMPLETION read as green instead of red.
*  Unknown/custom providers get nothing — the output-activity baseline still holds.
 *
 *  Every CLI here now speaks BOTH halves: an ambiguous "look at me" chime (which fires on
 *  completion as much as on a block) AND an explicit `done` that contradicts it, so the
 *  tracker's bell window can tell the two apart. Codex: OSC 9 + its notify program.
 *  Gemini: enableNotifications + the AfterAgent hook. OpenCode: its attention chime + a
 *  generated plugin. Aider has no chime at all — only a done — which is already honest. */
export function bellLaunchExtras(
  agentId: string,
  session: { runtime?: Record<string, unknown>; tui?: Record<string, unknown> } = {}
): { args: string[]; env: Record<string, string>; reason?: string } {
  const none = { args: [], env: {} }
  switch (agentId) {
    case 'codex':
      // Hand Codex the notify script too: its OSC 9 alone cannot tell turn-complete from
      // wants-approval, and the notify program (turn-complete ONLY) is what disambiguates.
      return { args: codexBellArgs(notifyHookPath() ?? undefined), env: {} }
    case 'gemini': {
      // The notification alone cannot say WHICH ("action-required prompts and session
      // completion" are one switch); the AfterAgent hook is the done that disambiguates it.
      const file = writeGenerated(
        'gemini-system-settings.json',
        geminiSystemSettings(
          readJson(geminiRealSystemSettingsPath()),
          notifyHookInvocation() ?? undefined,
          session.runtime
        )
      )
      return file ? { args: [], env: { GEMINI_CLI_SYSTEM_SETTINGS_PATH: file } } : none
    }
    case 'opencode': {
      const userTui = readJson(join(homedir(), '.config', 'opencode', 'tui.json'))
      const tui = writeGenerated('opencode-tui.json', opencodeTuiConfig(userTui, session.tui))
      if (!tui && Object.keys(session.tui ?? {}).length) return { ...none, reason: 'OpenCode next-launch TUI settings could not be materialized.' }
      if (!tui) return none
      const env: Record<string, string> = { OPENCODE_TUI_CONFIG: tui }
      // OpenCode has no hook config: its only verdict channel is a plugin. Both files must
      // land or we ship the chime alone — which is the ambiguous half, so the pane would
      // read every completion as attention.
      const script = notifyHookPath()
      const plugin = script ? writeGenerated('opencode-notify-plugin.mjs', opencodePluginSource(script)) : null
      let inherited: Record<string, unknown> = {}
      if (process.env.OPENCODE_CONFIG_CONTENT) {
        const errors: { error: number; offset: number; length: number }[] = []
        const parsed = parseJsonc(process.env.OPENCODE_CONFIG_CONTENT, errors, { allowTrailingComma: true, disallowComments: false })
        if (errors.length || !parsed || typeof parsed !== 'object' || Array.isArray(parsed)) {
          return { ...none, reason: 'OpenCode inline configuration is invalid and cannot be merged safely.' }
        }
        inherited = parsed as Record<string, unknown>
      }
      env.OPENCODE_CONFIG_CONTENT = opencodeConfig(plugin ?? undefined, session.runtime, inherited)
      return { args: [], env }
    }
    case 'aider': {
      const inv = notifyHookInvocation()
      return inv ? { args: [], env: aiderBellEnv(inv) } : none
    }
    default:
      return none
  }
}
