import { BrowserWindow } from 'electron'
import { join } from 'node:path'
import { existsSync } from 'node:fs'

/** Creates the main window with hardened webPreferences. */
export function createMainWindow(): BrowserWindow {
  // Window / taskbar icon = the product logo. In dev this resolves to build/icon.png; the
  // packaged app's icon is generated by electron-builder from that same source.
  const iconPath = join(__dirname, '../../build/icon.png')
  const win = new BrowserWindow({
    width: 1200,
    height: 800,
    backgroundColor: '#0a0a0a',
    title: 'MoggingLabs Workspace',
    ...(existsSync(iconPath) ? { icon: iconPath } : {}),
    webPreferences: {
      preload: join(__dirname, '../preload/index.js'),
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: true
    }
  })

  if (process.env.MOGGING_DEVLOG) {
    win.webContents.on('console-message', (_e, _level, message, line, source) => {
      console.log(`[renderer] ${message} (${source}:${line})`)
    })
    win.webContents.on('did-fail-load', (_e, code, desc, url) => {
      console.log(`[did-fail-load] ${code} ${desc} ${url}`)
    })
    win.webContents.on('render-process-gone', (_e, details) => {
      console.log(`[render-process-gone] ${details.reason}`)
    })
  }

  if (process.env.ELECTRON_RENDERER_URL) {
    void win.loadURL(process.env.ELECTRON_RENDERER_URL)
  } else {
    void win.loadFile(join(__dirname, '../renderer/index.html'))
  }

  return win
}
