import { app, BrowserWindow, session } from 'electron'
import { join } from 'node:path'
import { existsSync } from 'node:fs'

// ── Renderer lockdown (ADR 0016 §hardening) ─────────────────────────────────────────
// The trusted renderer's blast radius is pinned to zero before the account flow ships
// through it: no network of its own, no way to be navigated or window.open'd off the
// app document. The webview browser dock is untouched — its guests run out of process
// on partition sessions with their own guards (browser-dock.ts), never through here.

// MUST byte-match the meta tag in src/renderer/index.html — the LOCKDOWN smoke
// asserts the two agree, so a drift fails the sweep rather than shipping half a policy.
// style-src keeps 'unsafe-inline' ON PURPOSE: the design-token system writes inline
// style attributes/custom properties; "tightening" it away breaks every themed surface.
const RENDERER_CSP =
  "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; " +
  "connect-src 'none'; object-src 'none'; base-uri 'none'; form-action 'none'; frame-src 'none'"

// Interactive dev is the ONE exception, and only for connect-src: vite's HMR socket is
// a renderer-side WebSocket to the dev origin, which 'none' kills. A gate is not a dev
// run (every gate sets MOGGING_USERDATA) and a packaged app has no dev server — both
// get the shipped policy. electron.vite.config.ts applies the same relax to the meta
// tag under `serve`, same condition, so header and meta never disagree.
const interactiveDev = (): boolean =>
  !app.isPackaged && !!process.env.ELECTRON_RENDERER_URL && !process.env.MOGGING_USERDATA

const effectiveCsp = (): string =>
  interactiveDev() ? RENDERER_CSP.replace("connect-src 'none'", 'connect-src http: ws:') : RENDERER_CSP

// Observability for the LOCKDOWN smoke — main-side ground truth that the header
// actually attached and the guards actually fired (never exposed over IPC).
const lockdown = { policy: '', headerHits: 0, deniedNavs: [] as string[], deniedOpens: [] as string[] }
export const lockdownDebug = (): typeof lockdown => lockdown

/** The same CSP the meta tag declares, re-issued as a RESPONSE HEADER on the app's own
 *  documents — defense in depth: a compromised document can ignore a meta tag, not a
 *  header. defaultSession only (dock guests live on partition sessions and never pass
 *  through it), main-frame documents only, app origin only (devtools:// stays alone). */
function installCspHeader(): void {
  if (lockdown.policy) return // idempotent — one listener per session is Electron law
  lockdown.policy = effectiveCsp()
  const devOrigin = process.env.ELECTRON_RENDERER_URL ? new URL(process.env.ELECTRON_RENDERER_URL).origin : ''
  session.defaultSession.webRequest.onHeadersReceived((details, callback) => {
    const isAppDoc =
      details.resourceType === 'mainFrame' &&
      (details.url.startsWith('file:') || (!!devOrigin && details.url.startsWith(devOrigin)))
    if (!isAppDoc) {
      callback({})
      return
    }
    lockdown.headerHits += 1
    callback({ responseHeaders: { ...details.responseHeaders, 'Content-Security-Policy': [lockdown.policy] } })
  })
}

/** The trusted renderer can never leave its page or spawn one: window.open is denied
 *  flat (external links route through the browser:openExternal IPC handler ->
 *  shell.openExternal, explicitly — the account flow's only sanctioned outbound hop),
 *  and any navigation off the app origin is refused. The dock's guests keep their own
 *  handlers (browser-dock.ts wireGuest) — a guest's webContents is not this one. */
function installNavigationGuard(win: BrowserWindow): void {
  const devOrigin = process.env.ELECTRON_RENDERER_URL ? new URL(process.env.ELECTRON_RENDERER_URL).origin : ''
  const isAppUrl = (url: string): boolean =>
    url.startsWith('file:') || url === 'about:blank' || (!!devOrigin && url.startsWith(devOrigin))
  win.webContents.setWindowOpenHandler(({ url }) => {
    lockdown.deniedOpens.push(url)
    return { action: 'deny' }
  })
  const deny = (e: { preventDefault: () => void }, url: string): void => {
    if (isAppUrl(url)) return
    e.preventDefault()
    lockdown.deniedNavs.push(url)
  }
  win.webContents.on('will-navigate', deny)
  win.webContents.on('will-redirect', deny)
}

/** Creates the main window with hardened webPreferences. */
export function createMainWindow(opts: { largerThanScreen?: boolean } = {}): BrowserWindow {
  // Window / taskbar icon = the product logo. In dev this resolves to build/icon.png; the
  // packaged app's icon is generated by electron-builder from that same source.
  const iconPath = join(__dirname, '../../build/icon.png')
  const win = new BrowserWindow({
    width: 1200,
    height: 800,
    // Harness runs only (boot threads its `harness` flag here; production passes nothing):
    // gates were authored against this 1200-wide window, and CI's macOS runner has a
    // 1024-wide display. win.setSize past the display works on Windows/Linux but Cocoa
    // CLAMPS it unless the window was CREATED with enableLargerThanScreen — without this,
    // the geometry gates (EXPLORER's drag cap, BROWSER's dock settle) fail the screen, not
    // the product. macOS-only option; a no-op elsewhere.
    ...(opts.largerThanScreen ? { enableLargerThanScreen: true } : {}),
    // The floor under user resizing. 600 is sized against the titlebar's rigid parts at
    // its narrowest CSS state (lead ~70 + right cluster ~300 incl. the 140px Windows
    // controls reserve + gaps + a usable command box — see the compression block in
    // global.css; the two are a pair). VS Code ships 400×270 with a sparser bar; our
    // right cluster alone is ~300px, so 400 would overlap. 400 height keeps one pane
    // usable below the 44px bar.
    minWidth: 600,
    minHeight: 400,
    backgroundColor: '#0c0d0f', // matches --bg-app: no white flash, no seam behind the chrome
    // The window stays hidden until the renderer's first paint is ready
    // (`ready-to-show` below): the user never sees the empty-shell frame —
    // launch reads as instant instead of black -> white -> black.
    show: false,
    title: 'MoggingLabs Workspace',
    ...(existsSync(iconPath) ? { icon: iconPath } : {}),
    // Organic chrome: the app draws its own header (drag regions in CSS); only the
    // native window controls remain, overlaid by the OS — nothing "glued on top".
    titleBarStyle: 'hidden',
    ...(process.platform === 'darwin'
      // x:14 puts the three traffic lights ~66px in; the renderer's lead cluster clears
      // them with a matching inset, --traffic-light-inset in global.css. Move one, move
      // both. y centres the 16px lights in the 44px bar (--titlebar-h).
      ? { trafficLightPosition: { x: 14, y: 14 } }
      : {
          titleBarOverlay: {
            color: '#141518', // --bg-surface: the controls sit ON the top bar, one surface
            symbolColor: '#a9aeb6',
            // MUST equal --titlebar-h in global.css: this is the band the OS paints its
            // min/max/close into, and .titlebar-right reserves width for exactly it.
            height: 44
          }
        }),
    webPreferences: {
      preload: join(__dirname, '../preload/index.js'),
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: true,
      // The browser dock is an in-DOM <webview> (8/07 resize rework): the guest
      // page is a layout participant, so it resizes in LOCKSTEP with the chrome
      // (one compositor, no separate WebContentsView layer, no drag lag/
      // artifacts). The guest still runs OUT of process, isolated from this
      // renderer (its own partition/sandbox) — the page never enters the
      // trusted renderer's context (ADR 0002 / docs/13 posture preserved).
      webviewTag: true
    }
  })

  // The ADR 0016 lockdown (CSP header + flat-deny nav/open guards with the LOCKDOWN
  // gate's telemetry) subsumes the softer guards main grew in parallel — window.open is
  // denied with NO side effect (external links take the one sanctioned hop, the
  // browser:openExternal IPC handler, and the gate asserts both directions).
  installCspHeader()
  installNavigationGuard(win)

  // Defense in depth (ADR 0002 / docs/13): the dock's guests are the ONLY webviews the
  // app ever attaches. Force isolation regardless of what the element asked for, strip any
  // preload, and REFUSE any partition that isn't one of ours (persist:bdock.* / aweb.* /
  // aweb-mem.*) — so even a compromised renderer cannot attach a node-enabled webview or
  // point one at a foreign session. This is the belt to the renderer's suspenders.
  win.webContents.on('will-attach-webview', (event, webPreferences, params) => {
    delete webPreferences.preload
    webPreferences.nodeIntegration = false
    webPreferences.nodeIntegrationInSubFrames = false
    webPreferences.contextIsolation = true
    webPreferences.sandbox = true
    const partition = typeof params.partition === 'string' ? params.partition : ''
    if (!/^(persist:bdock\.|persist:aweb\.|aweb-mem\.)[a-zA-Z0-9_-]+$/.test(partition)) {
      event.preventDefault()
    }
  })

  if (process.env.MOGGING_DEVLOG) {
    win.webContents.on('console-message', (_e, _level, message, line, source) => {
      console.log(`[renderer] ${message} (${source}:${line})`)
    })
    win.webContents.on('did-fail-load', (_e, code, desc, url) => {
      console.log(`[did-fail-load] ${code} ${desc} ${url}`)
    })
    win.webContents.on('render-process-gone', (_e, details) => {
      console.log(`[render-process-gone] ${details.reason}`)
    })
  }

  // The two default-menu accelerators worth keeping, re-provided deliberately now that
  // Windows/Linux run menuless (src/main/menu.ts). before-input-event fires BEFORE the
  // renderer, so nothing goes here that a shell might want — no Ctrl+R (reverse-i-search),
  // no Ctrl+W (delete-word). F11 and the devtools chords have no terminal meaning.
  win.webContents.on('before-input-event', (event, input) => {
    if (input.type !== 'keyDown') return
    if (input.key === 'F11' && process.platform !== 'darwin') {
      event.preventDefault()
      win.setFullScreen(!win.isFullScreen())
      return
    }
    if (
      !app.isPackaged &&
      (input.key === 'F12' || (input.control && input.shift && input.key.toUpperCase() === 'I'))
    ) {
      event.preventDefault()
      win.webContents.toggleDevTools()
    }
  })

  // First paint ready -> reveal. The timer is the fail-open: if the renderer
  // never reaches ready-to-show (crash, dev-server stall), the window must
  // still appear rather than leave a silently invisible app.
  const reveal = (): void => {
    if (!win.isDestroyed() && !win.isVisible()) win.show()
  }
  win.once('ready-to-show', reveal)
  setTimeout(reveal, 4000)

  if (process.env.ELECTRON_RENDERER_URL) {
    void win.loadURL(process.env.ELECTRON_RENDERER_URL)
  } else {
    void win.loadFile(join(__dirname, '../renderer/index.html'))
  }

  return win
}
