# Generated by scripts/update-manifests.mjs — edit the templates there, not here.
cask "mogginglabs-workspace" do
  arch arm: "arm64", intel: "x64"

  version "0.3.0"
  sha256 arm:   "5b75f3412ca73ad7a4f164530b98658d76c7a706fad1791c2e6039d8dee52052",
         intel: "cec5ca4a7a13b80eb2590530066afe7e887113504672f58ec0ef623d3c85aac3"

  url "https://github.com/MoggingLabs/mogginglabs-workspace/releases/download/v#{version}/MoggingLabs.Workspace-#{version}-mac-#{arch}.dmg"
  name "MoggingLabs Workspace"
  desc "Multi-pane terminal workspace for AI coding agents"
  homepage "https://github.com/MoggingLabs/mogginglabs-workspace"

  auto_updates true

  app "MoggingLabs Workspace.app"

  zap trash: [
    "~/Library/Application Support/MoggingLabs",
    "~/Library/Application Support/MoggingLabs Workspace",
    "~/Library/Preferences/ai.mogginglabs.workspace.plist",
    "~/Library/Saved Application State/ai.mogginglabs.workspace.savedState",
  ]
end
