// The protocol-neutral MCP launcher. PURE — builds a source string, touches nothing.
//
// Lives outside src/main because it is the one thing about the CLI runtime worth testing
// on its own: a bug here is invisible in review (the launcher is a STRING, and a wrong
// filename inside it reads as plausibly as a right one) and silent at runtime (the wrong
// server starts and answers, it just answers about the wrong thing).

/**
 * Build the tiny launcher a managed MCP config points at.
 *
 * A CLI's MCP config may outlive the protocol release that wrote it, so the config names a
 * stable, unversioned path and THIS script forwards to the current versioned target. When
 * the process runs inside one of our panes (MOGGING_DAEMON_ENDPOINT is set), it forwards to
 * the protocol version that pane's daemon actually speaks instead — a config written by
 * v10 must not start a v10 server against a v11 daemon.
 *
 * The redirect changes WHICH VERSION runs. It must never change WHICH SCRIPT runs — which
 * is exactly what it used to do: the pane target was built with the literal
 * 'mogging-mcp.mjs', so the connection bridge's own launcher, generated by this same
 * function, forwarded every invocation to the HOUSE server. Inside a pane the endpoint is
 * always set, so that was every invocation: no agent could ever reach a connected service,
 * and ADR 0014's whole delivery path was dead while looking wired. basename(current) keeps
 * the script identity that the caller chose.
 */
export function stableMcpLauncherSource(target: string): string {
  return (
    '#!/usr/bin/env node\n' +
    "import { existsSync } from 'node:fs'\n" +
    "import { basename, dirname, join, relative } from 'node:path'\n" +
    "import { pathToFileURL } from 'node:url'\n" +
    `const current = ${JSON.stringify(target)}\n` +
    'let selected = current\n' +
    'const endpoint = process.env.MOGGING_DAEMON_ENDPOINT\n' +
    'if (endpoint) {\n' +
    '  const runRoot = dirname(dirname(dirname(current)))\n' +
    '  const segment = relative(runRoot, dirname(endpoint))\n' +
    "  if (/^(?:dev-)?v[1-9]\\d*$/.test(segment)) {\n" +
    // basename(current), NOT a literal: this redirect re-points the VERSION, never the script.
    '    const paneTarget = join(runRoot, segment, \'bin\', basename(current))\n' +
    '    if (existsSync(paneTarget)) selected = paneTarget\n' +
    '  }\n' +
    '}\n' +
    'await import(pathToFileURL(selected).href)\n'
  )
}
