import { execFileSync } from 'node:child_process'
import { removeTempDir } from './temp-dir'
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { afterAll, describe, expect, it } from 'vitest'
import { stableMcpLauncherSource } from '@backend/platform/mcp-launcher'

// THE ADR-0014 CRITICAL, pinned.
//
// A managed MCP config names a stable, unversioned path; this launcher forwards to the
// current versioned target, and when it runs inside one of our panes it forwards to the
// protocol version that pane's daemon speaks instead. That redirect is supposed to change
// WHICH VERSION runs. It changed WHICH SCRIPT runs: the pane target was assembled with the
// literal 'mogging-mcp.mjs', so the connection bridge's own launcher — generated by this
// same function — forwarded to the HOUSE server. Inside a pane MOGGING_DAEMON_ENDPOINT is
// always set, so that was every invocation. No agent could reach a connected service, and
// the failure is invisible twice over: the launcher is a string, and the wrong server
// starts and answers perfectly well about the wrong thing.
//
// So this test RUNS the generated script rather than reading it. A string assertion would
// have been satisfied by the broken version too.

const roots: string[] = []
afterAll(() => {
  for (const r of roots) removeTempDir(r)
})

/** A runtime tree with two protocol versions, each holding both entry scripts. */
function world(): { runRoot: string; v10: string; v11: string } {
  const base = mkdtempSync(join(tmpdir(), 'mcplaunch-'))
  roots.push(base)
  const runRoot = join(base, 'run')
  for (const v of ['v10', 'v11']) {
    const bin = join(runRoot, v, 'bin')
    mkdirSync(bin, { recursive: true })
    for (const script of ['mogging-mcp.mjs', 'mogging-connection.mjs']) {
      // Each target announces exactly who it is.
      writeFileSync(join(bin, script), `console.log(${JSON.stringify(v + '/' + script)})\n`, 'utf8')
    }
      }
  return { runRoot, v10: join(runRoot, 'v10'), v11: join(runRoot, 'v11') }
}

/** Write the launcher for `target` and run it, returning what the imported script printed. */
function run(target: string, endpoint?: string): string {
  const launcher = join(mkdtempSync(join(tmpdir(), 'mcpl-')), 'launcher.mjs')
  roots.push(launcher)
  writeFileSync(launcher, stableMcpLauncherSource(target), 'utf8')
  const env = { ...process.env }
  delete env.MOGGING_DAEMON_ENDPOINT
  if (endpoint) env.MOGGING_DAEMON_ENDPOINT = endpoint
  return execFileSync(process.execPath, [launcher], { encoding: 'utf8', env }).trim()
}

describe('stableMcpLauncherSource', () => {
  it('runs its own target when no pane endpoint is set', () => {
    const w = world()
    expect(run(join(w.v11, 'bin', 'mogging-connection.mjs'))).toBe('v11/mogging-connection.mjs')
    expect(run(join(w.v11, 'bin', 'mogging-mcp.mjs'))).toBe('v11/mogging-mcp.mjs')
  })

  // THE regression: a config written by v10, launched inside a v11 pane.
  it('re-points the VERSION and keeps the SCRIPT — the connection bridge stays the bridge', () => {
    const w = world()
    const out = run(join(w.v10, 'bin', 'mogging-connection.mjs'), join(w.runRoot, 'v11', 'endpoint.json'))
    expect(out).toBe('v11/mogging-connection.mjs') // was 'v11/mogging-mcp.mjs' — the house server
  })

  it('re-points the house server to the pane version too', () => {
    const w = world()
    const out = run(join(w.v10, 'bin', 'mogging-mcp.mjs'), join(w.runRoot, 'v11', 'endpoint.json'))
    expect(out).toBe('v11/mogging-mcp.mjs')
  })

  it('ignores an endpoint outside a recognisable version segment', () => {
    const w = world()
    const out = run(join(w.v11, 'bin', 'mogging-connection.mjs'), join(w.runRoot, 'not-a-version', 'endpoint.json'))
    expect(out).toBe('v11/mogging-connection.mjs')
  })

  it('falls back to its own target when the pane version has no such script', () => {
    const w = world()
    rmSync(join(w.v10, 'bin', 'mogging-connection.mjs'))
    const out = run(join(w.v11, 'bin', 'mogging-connection.mjs'), join(w.runRoot, 'v10', 'endpoint.json'))
    expect(out).toBe('v11/mogging-connection.mjs')
  })

  it('accepts the dev channel segment', () => {
    const base = mkdtempSync(join(tmpdir(), 'mcpdev-'))
    roots.push(base)
    const runRoot = join(base, 'run')
    const bin = join(runRoot, 'dev-v11', 'bin')
    mkdirSync(bin, { recursive: true })
    writeFileSync(join(bin, 'mogging-connection.mjs'), "console.log('dev-v11/mogging-connection.mjs')\n", 'utf8')
    const src = join(runRoot, 'dev-v10', 'bin')
    mkdirSync(src, { recursive: true })
    writeFileSync(join(src, 'mogging-connection.mjs'), "console.log('dev-v10/mogging-connection.mjs')\n", 'utf8')
    const out = run(join(src, 'mogging-connection.mjs'), join(runRoot, 'dev-v11', 'endpoint.json'))
    expect(out).toBe('dev-v11/mogging-connection.mjs')
  })
})
